<a href="https://colab.research.google.com/github/mjibral466/latihanMjr/blob/main/latihan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [64]:
import numpy as np
import pandas as pd

**persamaan**

In [65]:
x = [
    [
        [-61, 11, 7],
        [20, 67, 8],
        [38, 16, -98]
    ],
    [
        [-109, 14, 57],
        [2, -64, 24],
        [38, 4, -85]
    ],
    [
        [-62, 3, 13],
        [17, -93, 39],
        [20, 8, -69]
    ],
    [
        [105, 28, 112],
        [56, 97, 84],
        [20, 81, -60]
    ],
    [
        [-87, 23, 23],
        [11, 95, 45],
        [18, 44, -108]
    ]
]

y = [
    [-969, 79, -265],
    [78, -1, -382],
    [-970, -849, -449],
    [198, -314, 193],
    [882, -17, 945]
]


**Function Utama diagonally dominant**

In [66]:
def notDiagonallyDominant(x):
  diag = np.diag(np.abs(x))
  off_diag = np.sum(np.abs(x), axis = 1) - diag

  if(np.all(diag <= off_diag)):
    return False
  else:
    return True


**Fungsi Gauss Seidel**

In [67]:
def gauss_seidel(matrix_x, matrix_y, max_iteration = 16, tolerance = 0.001):
  xs = np.array(matrix_x)
  ys = np.array(matrix_y)

  if(notDiagonallyDominant(xs)):
    return "Matrix tidak diagonally dominant"

  diagonal = np.diag(np.abs(xs)) #ambil diagonal
  xs = -xs # ubah tanda
  np.fill_diagonal(xs,0) # menyimpan sisa matrix selain diagonal

  x_old = np.zeros(xs.shape[0]) # untuk iterasi awal

  for idx in range(max_iteration):
    x_new = np.array(x_old) #untuk nilai baru setelah di iterasi

    for j, row in enumerate(xs):
      x_new[j] = (ys[j] + np.dot(row, x_new)) / diagonal[j] #rumus gauss seidel

    x_new = np.array(x_new)

    print(f"Iterasi ke-{idx+1}: {x_new}")

    error = np.sqrt((x_new - x_old)**2)/(np.sqrt(x_new))# cek error
    print(f"Error: {x_new} {x_old} = {error}")

    if(np.sqrt(np.sum((x_new - x_old)**2)) < tolerance):
      print("konvergen")
      return x_new

    x_old = x_new


Main

In [68]:
def main():
  for idx, (matrix_x, matrix_y) in enumerate(zip(x,y)):
    print(f"Matrix ke-{idx+1}")
    print(f"matrix atau persamaan {np.array(matrix_x)}")
    gauss_seidel(matrix_x, matrix_y)
    print()


In [69]:
main()

Matrix ke-1
matrix atau persamaan [[-61  11   7]
 [ 20  67   8]
 [ 38  16 -98]]

Matrix ke-2
matrix atau persamaan [[-109   14   57]
 [   2  -64   24]
 [  38    4  -85]]

Matrix ke-3
matrix atau persamaan [[-62   3  13]
 [ 17 -93  39]
 [ 20   8 -69]]

Matrix ke-4
matrix atau persamaan [[105  28 112]
 [ 56  97  84]
 [ 20  81 -60]]
Iterasi ke-1: [ 1.88571429 -4.3257732   8.42788905]
Error: [ 1.88571429 -4.3257732   8.42788905] [0. 0. 0.] = [1.37321312        nan 2.90308268]
Iterasi ke-2: [-5.95049452 -7.10015451 14.78537343]
Error: [-5.95049452 -7.10015451 14.78537343] [ 1.88571429 -4.3257732   8.42788905] = [       nan        nan 1.65336657]
Iterasi ke-3: [-11.99197617  -9.1177392   19.52293998]
Error: [-11.99197617  -9.1177392   19.52293998] [-5.95049452 -7.10015451 14.78537343] = [       nan        nan 1.07221706]
Iterasi ke-4: [-16.5073579  -10.61355583  23.04741967]
Error: [-16.5073579  -10.61355583  23.04741967] [-11.99197617  -9.1177392   19.52293998] = [      nan       nan 0.7341

/tmp/ipykernel_4706/1983786846.py:24: RuntimeWarning: invalid value encountered in sqrt
  error = np.sqrt((x_new - x_old)**2)/(np.sqrt(x_new))# cek error
